apiVersion: apps/v1
kind: Deployment
metadata:
  name: recomendation-deployment
  namespace: viniciusfreire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viniciusfreire-playlist-recommender
  template:
    metadata:
      labels:
        app: viniciusfreire-playlist-recommender
    spec:
      initContainers:
        - name: model-generator
          image: vinciusb/model_generator:1.0.0
          volumeMounts:
          - mountPath: /tmp/data
            name: shared-storage
      containers:
        - name: recomendation-engine
          image: vinciusb/recomendation_engine:1.0.0
          ports:
            - containerPort: 5000
          volumeMounts:
          - mountPath: /tmp/data
            name: shared-storage
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: project2-pvc-viniciusfreire

---

apiVersion: v1
kind: Service
metadata:
  name: recomendation-service
  namespace: viniciusfreire
spec:
  selector:
    app: viniciusfreire-playlist-recommender
  ports:
    - protocol: TCP
      port: 52060
      targetPort: 5000
      nodePort: 32000
  type: NodePort

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-viniciusfreire
  namespace: viniciusfreire
spec:
  storageClassName: default-storage-class-viniciusfreire
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      namespace: viniciusfreire
  volumeName: project2-pv2-viniciusfreire

# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   namespace: viniciusfreire
#   name: project2-pv2-viniciusfreire
# spec:
#   capacity:
#     storage: 500Mi
#   storageClassName: default-storage-class-viniciusfreire
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Recycle
#   hostPath:
#     path: /home/vinicius/UFMG/9p/CN/TP2/project2-pv2