name: Auto Tag on Commit

on:
  push:
    branches:
      - main  # Change this to your default branch name if it's not 'main'

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git user
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Generate new tag
      id: tag
      run: |
        # Check the latest tag
        latest_tag=$(git describe --tags --abbrev=0 || echo "0.0.0")
        echo "Latest tag: $latest_tag"

        tag_date=$(date +'%Y/%m/%dT%H-%M-%S')

        echo "New tag: $tag_date"
        echo "new_tag=$tag_date" >> $GITHUB_ENV

    - name: Push new tag
      run: |
        git tag ${{ env.new_tag }}
        git push origin ${{ env.new_tag }}
        echo "Pushed tag: ${{ env.new_tag }}"
