name: Auto Tag on Commit

on:
  push:
    branches:
      - main  # Change this to your default branch name if it's not 'main'

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - run: git fetch --prune --unshallow

    - name: Set up Git user
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Generate new tag
      id: tag
      run: |
        # Check the latest tag
        echo $(git describe --tags --abbrev=0)
        latest_tag=$(git describe --tags --abbrev=0 || echo "1.0.0")
        if [[ "$latest_tag" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
          major=${BASH_REMATCH[1]}
          minor=${BASH_REMATCH[2]}
          patch=${BASH_REMATCH[3]}
        else
          major=1
          minor=0
          patch=0
        fi
        echo "Latest tag: $latest_tag"
        new_patch=$((patch + 1))

        new_tag="$major.$minor.$new_patch"

        echo "New tag: $new_tag"
        echo "new_tag=$new_tag" >> $GITHUB_ENV

    - name: Push new tag
      run: |
        git tag ${{ env.new_tag }}
        git push origin ${{ env.new_tag }}
        echo "Pushed tag: ${{ env.new_tag }}"
